using System.Linq;
using FluentPatcher.Generator.Models;
using System.Text;

namespace FluentPatcher.Generator;

/// <summary>
/// Generates the PatchContext class that tracks all changes during patching.
/// </summary>
internal static class ContextGenerator
{
    public static string Generate(PatcherModel model)
    {
        var sb = new StringBuilder();
            
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Collections;");
        sb.AppendLine("using FluentPatcher.Context;");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace}");
        sb.AppendLine("{");
            
        // Generate the PatchContext class
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Tracks changes made during patching of {model.ClassName}.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    public sealed class {model.ContextClassName} : PatchContextBase");
        sb.AppendLine("    {");

        // Helper for printing values in summaries.
        sb.AppendLine("        private static string FormatChangeValue(object? value)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (value is null) return \"null\";");
        sb.AppendLine();
        sb.AppendLine("            // Keep strings human-readable and consistent with previous output.");
        sb.AppendLine("            if (value is string s) return $\"'{s}'\";");
        sb.AppendLine();
        sb.AppendLine("            // For complex types and collections, JSON is usually much more helpful than TypeName.ToString().");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                var t = value.GetType();");
        sb.AppendLine();
        sb.AppendLine("                // Don't JSON-encode primitives/enums/DateTime/etc. — keep previous compact formatting.");
        sb.AppendLine("                if (t.IsPrimitive || t.IsEnum || value is decimal || value is DateTime || value is DateTimeOffset || value is Guid || value is TimeSpan)");
        sb.AppendLine("                    return $\"'{value}'\";");
        sb.AppendLine();
        sb.AppendLine("                // Collections (except string) and POCOs => JSON.");
        sb.AppendLine("                if (value is IEnumerable && value is not IDictionary)");
        sb.AppendLine("                    return JsonSerializer.Serialize(value);");
        sb.AppendLine();
        sb.AppendLine("                // Complex reference types => JSON.");
        sb.AppendLine("                if (!t.IsValueType)");
        sb.AppendLine("                    return JsonSerializer.Serialize(value);");
        sb.AppendLine("            }");
        sb.AppendLine("            catch");
        sb.AppendLine("            {");
        sb.AppendLine("                // ignore and fallback below");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            return $\"'{value}'\";");
        sb.AppendLine("        }");
        sb.AppendLine();
            
        // Generate properties for each field
        foreach (var prop in model.Properties)
        {
            // Use target type metadata so generated context does not rely on local using directives.
            var valueTypeName = prop.TargetPropertyTypeName ?? prop.PatchableInnerTypeFullName ?? "object";
            
            sb.AppendLine($"        #region {prop.Name}");
            sb.AppendLine();
                
            // Changed flag
            sb.AppendLine($"        /// <summary>Indicates whether {prop.Name} was changed.</summary>");
            sb.AppendLine($"        public bool {prop.Name}Changed {{ get; internal set; }}");
            sb.AppendLine();
                
            // Old value
            sb.AppendLine($"        /// <summary>The original value of {prop.Name} before patching.</summary>");
            sb.AppendLine($"        public {valueTypeName} Old{prop.Name} {{ get; internal set; }} = default!;");
            sb.AppendLine();
                
            // New value
            sb.AppendLine($"        /// <summary>The new value of {prop.Name} after patching.</summary>");
            sb.AppendLine($"        public {valueTypeName} New{prop.Name} {{ get; internal set; }} = default!;");
            sb.AppendLine();
                
            sb.AppendLine($"        #endregion");
            sb.AppendLine();
        }
            
        // Generate HasChanges method
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Returns true if any property was changed during patching.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public override bool HasChanges()");
        sb.AppendLine("        {");
            
        var changedProps = model.Properties;
        if (changedProps.Count == 0)
        {
            sb.AppendLine("            return false;");
        }
        else
        {
            sb.Append("            return ");
            sb.AppendLine(string.Join(" ||\n                   ", changedProps.Select(p => $"{p.Name}Changed")));
            sb.AppendLine("                   ;");
        }
            
        sb.AppendLine("        }");
        sb.AppendLine();
            
        // Generate GetChangedValues method for easy access
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Gets a dictionary of all changed property names and their new values.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public Dictionary<string, object?> GetChangedValues()");
        sb.AppendLine("        {");
        sb.AppendLine("            var result = new Dictionary<string, object?>();");
            
        foreach (var prop in changedProps)
        {
            sb.AppendLine($"            if ({prop.Name}Changed) result[\"{prop.Name}\"] = New{prop.Name};");
        }
            
        sb.AppendLine("            return result;");
        sb.AppendLine("        }");
        sb.AppendLine();
            
        // Generate summary method
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Gets a human-readable summary of all changes.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public string GetChangesSummary()");
        sb.AppendLine("        {");
        sb.AppendLine("            var changes = new List<string>();");
            
        foreach (var prop in changedProps)
        {
            sb.AppendLine($"            if ({prop.Name}Changed) changes.Add($\"{prop.Name}: {{FormatChangeValue(Old{prop.Name})}} -> {{FormatChangeValue(New{prop.Name})}}\");");
        }
            
        sb.AppendLine("            return string.Join(\"\\n\", changes);");
        sb.AppendLine("        }");
            
        sb.AppendLine("    }");
        sb.AppendLine("}");
            
        return sb.ToString();
    }
}