using FluentPatcher.Generator.Models;
using System.Text;

namespace FluentPatcher.Generator;

/// <summary>
/// Generates extension methods to apply DTO patches to entities.
/// </summary>
internal static class PatcherClassGenerator
{
    public static string Generate(PatcherModel model)
    {
        var sb = new StringBuilder();
            
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using FluentPatcher;");
        sb.AppendLine("using FluentPatcher.Context;");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace}");
        sb.AppendLine("{");
            
        // Generate static extensions class
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Extension methods for applying {model.ClassName} patches to entities.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static class {model.ExtensionClassName}");
        sb.AppendLine("    {");
            
        // Main extension: generic ApplyTo with PatchResult
        sb.AppendLine("        /// <summary>");
        sb.AppendLine($"        /// Applies this {model.ClassName} patch to the target entity and returns the result with change context.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        /// <typeparam name=\"TEntity\">The type of entity to patch.</typeparam>");
        sb.AppendLine("        /// <param name=\"patch\">The patch DTO.</param>");
        sb.AppendLine("        /// <param name=\"existing\">The existing entity to patch.</param>");
        sb.AppendLine("        /// <param name=\"cloneEntity\">Optional clone factory. When null, a shallow clone is created via Activator.</param>");
        sb.AppendLine("        /// <param name=\"options\">Optional patch behavior overrides for this call.</param>");
        sb.AppendLine($"        /// <returns>A PatchResult containing the updated entity and {model.ContextClassName}.</returns>");
        sb.AppendLine($"        public static PatchResult<TEntity, {model.ContextClassName}> ApplyTo<TEntity>(");
        sb.AppendLine($"            this {model.ClassName} patch,");
        sb.AppendLine($"            TEntity existing,");
        sb.AppendLine($"            Func<TEntity, TEntity>? cloneEntity = null,");
        sb.AppendLine($"            PatchOptions? options = null) where TEntity : class");
        sb.AppendLine("        {");
        sb.AppendLine("            var entity = ApplyPatchInternal(existing, patch, out var context, cloneEntity, options);");
        sb.AppendLine($"            return new PatchResult<TEntity, {model.ContextClassName}>(entity, context);");
        sb.AppendLine("        }");
        sb.AppendLine();
            
        sb.AppendLine("        /// <summary>");
        sb.AppendLine($"        /// Applies this {model.ClassName} patch to the target entity in-place and returns the change context.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        /// <typeparam name=\"TEntity\">The type of entity to patch.</typeparam>");
        sb.AppendLine("        /// <param name=\"patch\">The patch DTO.</param>");
        sb.AppendLine("        /// <param name=\"existing\">The existing entity to patch.</param>");
        sb.AppendLine("        /// <param name=\"options\">Optional patch behavior overrides for this call.</param>");
        sb.AppendLine($"        public static {model.ContextClassName} ApplyInto<TEntity>(");
        sb.AppendLine($"            this {model.ClassName} patch,");
        sb.AppendLine($"            TEntity existing,");
        sb.AppendLine($"            PatchOptions? options = null) where TEntity : class");
        sb.AppendLine("        {");
        sb.AppendLine("            _ = ApplyPatchInternal(existing, patch, out var context, static e => e, options);");
        sb.AppendLine("            return context;");
        sb.AppendLine("        }");
        sb.AppendLine();
            
        // Internal core logic reused by all entry points
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Core implementation that applies the patch and outputs context.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine($"        private static TEntity ApplyPatchInternal<TEntity>(");
        sb.AppendLine($"            TEntity existing,");
        sb.AppendLine($"            {model.ClassName} patch,");
        sb.AppendLine($"            out {model.ContextClassName} context,");
        sb.AppendLine($"            Func<TEntity, TEntity>? cloneEntity = null,");
        sb.AppendLine($"            PatchOptions? options = null) where TEntity : class");
        sb.AppendLine("        {");
        sb.AppendLine("            if (existing == null) throw new ArgumentNullException(nameof(existing));");
        sb.AppendLine("            if (patch == null) throw new ArgumentNullException(nameof(patch));");
        sb.AppendLine();
        sb.AppendLine("            // Work on a clone by default; custom clone factories may choose in-place mutation.");
        sb.AppendLine("            var updated = cloneEntity != null ? cloneEntity(existing) : ShallowClone(existing);");
        sb.AppendLine($"            context = new {model.ContextClassName}();");
        sb.AppendLine("            var entityType = typeof(TEntity);");
        sb.AppendLine();
            
        // Generate patch logic for each property
        foreach (var prop in model.Properties)
        {
            GeneratePropertyPatchCode(sb, prop);
        }
            
        sb.AppendLine("            return updated;");
        sb.AppendLine("        }");
        sb.AppendLine();
            
        // Helper: shallow clone using reflection
        sb.AppendLine("        private static TEntity ShallowClone<TEntity>(TEntity source) where TEntity : class");
        sb.AppendLine("        {");
        sb.AppendLine("            var type = typeof(TEntity);");
        sb.AppendLine("            var clone = (TEntity)Activator.CreateInstance(type, nonPublic: true)!;");
        sb.AppendLine("            foreach (var prop in type.GetProperties(System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic))");
        sb.AppendLine("            {");
        sb.AppendLine("                if (!prop.CanRead || !prop.CanWrite) continue;");
        sb.AppendLine("                if (prop.GetIndexParameters().Length != 0) continue;");
        sb.AppendLine("                var value = prop.GetValue(source);");
        sb.AppendLine("                prop.SetValue(clone, value);");
        sb.AppendLine("            }");
        sb.AppendLine("            return clone;");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        private static bool AreCollectionValuesEqual(object? first, object? second, PatchOptions? options)");
        sb.AppendLine("        {");
        sb.AppendLine("            var comparison = options?.CollectionComparison ?? PatchOptions.DefaultCollectionComparison;");
        sb.AppendLine("            if (comparison == CollectionChangeComparison.Reference)");
        sb.AppendLine("                return Equals(first, second);");
        sb.AppendLine();
        sb.AppendLine("            if (ReferenceEquals(first, second)) return true;");
        sb.AppendLine("            if (first == null || second == null) return false;");
        sb.AppendLine("            if (first is not IEnumerable firstEnumerable || second is not IEnumerable secondEnumerable)");
        sb.AppendLine("                return Equals(first, second);");
        sb.AppendLine();
        sb.AppendLine("            var firstEnumerator = firstEnumerable.GetEnumerator();");
        sb.AppendLine("            var secondEnumerator = secondEnumerable.GetEnumerator();");
        sb.AppendLine("            try");
        sb.AppendLine("            {");
        sb.AppendLine("                while (true)");
        sb.AppendLine("                {");
        sb.AppendLine("                    var firstHasValue = firstEnumerator.MoveNext();");
        sb.AppendLine("                    var secondHasValue = secondEnumerator.MoveNext();");
        sb.AppendLine("                    if (firstHasValue != secondHasValue) return false;");
        sb.AppendLine("                    if (!firstHasValue) return true;");
        sb.AppendLine("                    if (!Equals(firstEnumerator.Current, secondEnumerator.Current)) return false;");
        sb.AppendLine("                }");
        sb.AppendLine("            }");
        sb.AppendLine("            finally");
        sb.AppendLine("            {");
        sb.AppendLine("                (firstEnumerator as IDisposable)?.Dispose();");
        sb.AppendLine("                (secondEnumerator as IDisposable)?.Dispose();");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
            
        // Convenience extension that ignores context and returns only entity
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Applies the patch and returns only the updated entity.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine($"        public static TEntity ApplyToEntity<TEntity>(");
        sb.AppendLine($"            this {model.ClassName} patch,");
        sb.AppendLine($"            TEntity existing,");
        sb.AppendLine($"            Func<TEntity, TEntity>? cloneEntity = null,");
        sb.AppendLine($"            PatchOptions? options = null) where TEntity : class");
        sb.AppendLine("        {");
        sb.AppendLine("            return ApplyTo(patch, existing, cloneEntity, options).Entity;");
        sb.AppendLine("        }");
        sb.AppendLine();
            
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Applies the patch in-place and returns only the updated entity.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine($"        public static TEntity ApplyToEntityInPlace<TEntity>(");
        sb.AppendLine($"            this {model.ClassName} patch,");
        sb.AppendLine($"            TEntity existing,");
        sb.AppendLine($"            PatchOptions? options = null) where TEntity : class");
        sb.AppendLine("        {");
        sb.AppendLine("            _ = ApplyInto(patch, existing, options);");
        sb.AppendLine("            return existing;");
        sb.AppendLine("        }");
        sb.AppendLine();
            
        // Convenience extension that returns only context
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Applies the patch and returns only the change context.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine($"        public static {model.ContextClassName} ApplyToContext<TEntity>(");
        sb.AppendLine($"            this {model.ClassName} patch,");
        sb.AppendLine($"            TEntity existing,");
        sb.AppendLine($"            Func<TEntity, TEntity>? cloneEntity = null,");
        sb.AppendLine($"            PatchOptions? options = null) where TEntity : class");
        sb.AppendLine("        {");
        sb.AppendLine("            return ApplyTo(patch, existing, cloneEntity, options).Context;");
        sb.AppendLine("        }");
        sb.AppendLine();
            
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Applies the patch in-place and returns only the change context.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine($"        public static {model.ContextClassName} ApplyToContextInPlace<TEntity>(");
        sb.AppendLine($"            this {model.ClassName} patch,");
        sb.AppendLine($"            TEntity existing,");
        sb.AppendLine($"            PatchOptions? options = null) where TEntity : class");
        sb.AppendLine("        {");
        sb.AppendLine("            return ApplyInto(patch, existing, options);");
        sb.AppendLine("        }");
        sb.AppendLine();
            
        sb.AppendLine("    }");
        sb.AppendLine("}");
            
        return sb.ToString();
    }

    private static void GeneratePropertyPatchCode(StringBuilder sb, PropertyModel prop)
    {
        var targetProp = prop.EffectiveTargetName;
            
        sb.AppendLine($"            // Patch {prop.Name}");
        sb.AppendLine($"            var prop{prop.Name} = entityType.GetProperty(\"{targetProp}\", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic);");
        sb.AppendLine($"            if (prop{prop.Name} != null && prop{prop.Name}.CanWrite)");
        sb.AppendLine("            {");
        GeneratePatchablePropertyCode(sb, prop);
        sb.AppendLine("            }");
        sb.AppendLine();
    }

    private static void GeneratePatchablePropertyCode(StringBuilder sb, PropertyModel prop)
    {
        // All properties are Patchable<T> - check HasValue
        var targetType = prop.TargetPropertyTypeName ?? prop.PatchableInnerTypeFullName ?? "object";
        var nullForgivingSuffix = prop.IsTargetPropertyNullable ? string.Empty : "!";

        sb.AppendLine($"                var existing{prop.Name}Value = prop{prop.Name}.GetValue(existing);");
        sb.AppendLine($"                context.Old{prop.Name} = ({targetType})existing{prop.Name}Value{nullForgivingSuffix};");
        sb.AppendLine($"                if (patch.{prop.Name}.HasValue)");
        sb.AppendLine("                {");
        sb.AppendLine($"                    var patchValue = patch.{prop.Name}.Value{nullForgivingSuffix};");
        var equalityExpression = prop.IsCollection
            ? $"AreCollectionValuesEqual(existing{prop.Name}Value, patchValue, options)"
            : $"Equals(existing{prop.Name}Value, patchValue)";

        sb.AppendLine($"                    if (!{equalityExpression})");
        sb.AppendLine("                    {");
        sb.AppendLine($"                        context.New{prop.Name} = ({targetType})patchValue{nullForgivingSuffix};");
        sb.AppendLine($"                        context.{prop.Name}Changed = true;");
        sb.AppendLine($"                        prop{prop.Name}.SetValue(updated, patchValue);");
        sb.AppendLine("                    }");
        sb.AppendLine("                    else");
        sb.AppendLine("                    {");
        sb.AppendLine($"                        context.New{prop.Name} = ({targetType})existing{prop.Name}Value{nullForgivingSuffix};");
        sb.AppendLine("                    }");
        sb.AppendLine("                }");
        sb.AppendLine("                else");
        sb.AppendLine("                {");
        sb.AppendLine($"                    context.New{prop.Name} = ({targetType})existing{prop.Name}Value{nullForgivingSuffix};");
        sb.AppendLine("                }");
    }
}
